name: Local
values:
  - key: baseURL
    value: 'http://localhost:3000'
    type: default
    enabled: true
  - key: userToken
    value: ''
    type: secret
    enabled: true
  - key: adminToken
    value: ''
    type: secret
    enabled: true
